# Generated by Django 2.1.3 on 2021-05-08 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_album', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=50)),
                ('fecha', models.DateField()),
                ('imagen', models.ImageField(upload_to='')),
                ('totaltracks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='artista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_artista', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=30)),
                ('descripcion', models.TextField(max_length=300)),
                ('noticias', models.TextField(max_length=300)),
                ('albums', models.ManyToManyField(to='musicapp.album')),
            ],
        ),
        migrations.CreateModel(
            name='cancion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cancion', models.CharField(max_length=50)),
                ('titulo', models.TextField(max_length=50)),
                ('duracion', models.TextField(max_length=5)),
                ('año', models.IntegerField()),
                ('albumes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.album')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artista')),
            ],
        ),
        migrations.CreateModel(
            name='episodio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_episodio', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=100)),
                ('duracion', models.TextField(max_length=5)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_playlist', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=100)),
                ('descripcion', models.TextField(max_length=200)),
                ('duracion', models.TextField(max_length=5)),
                ('año', models.IntegerField()),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.album')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artista')),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.cancion')),
            ],
        ),
        migrations.CreateModel(
            name='podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_podcast', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=100)),
                ('imagen', models.ImageField(upload_to='')),
                ('totalepisodios', models.IntegerField()),
                ('fecha', models.DateField()),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artista')),
                ('episodios', models.ManyToManyField(to='musicapp.episodio')),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.CharField(max_length=50)),
                ('nombre', models.TextField(max_length=100)),
                ('playlist', models.ManyToManyField(to='musicapp.playlist')),
            ],
        ),
        migrations.AddField(
            model_name='episodio',
            name='podcasts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.podcast'),
        ),
        migrations.AddField(
            model_name='artista',
            name='canciones',
            field=models.ManyToManyField(to='musicapp.cancion'),
        ),
        migrations.AddField(
            model_name='album',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artista'),
        ),
        migrations.AddField(
            model_name='album',
            name='canciones',
            field=models.ManyToManyField(to='musicapp.cancion'),
        ),
    ]
